[advisories]
ignore = [
    # TODO(geofmureithi): track https://github.com/launchbadge/sqlx/issues/4082
    "RUSTSEC-2023-0071",
    "RUSTSEC-2025-0052",
    "RUSTSEC-2024-0384",
]

[output]
quiet = false
deny = ["warnings"]
